datagrid:
    issue-grid:
        extended_entity_name: %oro_issue.entity.class%
        source:
            type: orm
            acl_resource: oro_issue_view
            query:
                select:
                    - issue.id
                    - issue.code
                    - issue.type
                    - issue.summary
                    - issuePriority.label as priorityLabel
                    - issuePriority.order as priorityOrder
                    - issueResolution.label as resolutionLabel
                    - CONCAT(issueReporter.firstName, CONCAT(' ', issueReporter.lastName)) as issueReporterName
                    - CONCAT(issueAssignee.firstName, CONCAT(' ', issueAssignee.lastName)) as issueAssigneeName
                    - issueAssignee.id assigneeId
                    - issueReporter.id reporterId
                    - issue.createdAt
                    - issue.updatedAt
                    - workflowStep.label as workflowStepLabel
                from:
                    - { table: %oro_issue.entity.class%, alias: issue }

                join:
                    left:
                        - { join: issue.priority, alias: issuePriority }
                        - { join: issue.resolution, alias: issueResolution }
                        - { join: issue.workflowStep, alias: workflowStep }
                        - { join: issue.reporter, alias: issueReporter }
                        - { join: issue.assignee, alias: issueAssignee }
        columns:
            code:
                label:         oro.issue.code_label
            type:
                label:         oro.issue.type_label
            summary:
                label:         oro.issue.summary_label
            priorityLabel:
                label:         oro.issue.priority_label
            resolutionLabel:
                label:         oro.issue.resolution_label
            issueReporterName:
                type:          twig
                label:         oro.issue.reporter_label
                frontend_type: html
                template:      OroIssueBundle:Issue:Datagrid/Property/reporter.html.twig
            issueAssigneeName:
                type:          twig
                label:         oro.issue.assignee_label
                frontend_type: html
                template:      OroIssueBundle:Issue:Datagrid/Property/assignee.html.twig
            createdAt:
                label:         oro.issue.created_label
                frontend_type: datetime
            updatedAt:
                label:         oro.issue.updated_label
                frontend_type: datetime
            workflowStepLabel:
                label:         oro.issue.workflow_step_label
        sorters:
            columns:
                code:
                    data_name: issue.code
                type:
                    data_name: issue.type
                summary:
                    data_name: issue.summary
                priorityLabel:
                    data_name: issuePriority.order
                resolutionLabel:
                    data_name: resolutionLabel
                issueReporterName:
                    data_name: issueReporterName
                issueAssigneeName:
                    data_name: issueAssigneeName
                createdAt:
                    data_name: issue.createdAt
                updatedAt:
                    data_name: issue.updatedAt
                workflowStepLabel:
                    data_name: workflowStep.stepOrder
            default:
                updatedAt: DESC
        filters:
            columns:
                code:
                    type:      string
                    data_name: issue.code
                type:
                    type:      choice
                    data_name: issue.type
                    options:
                        field_options:
                            choices: @oro_issue.grid_helper->getTypeChoices
                            translatable_options: false
                summary:
                    type:      string
                    data_name: issue.summary
                priority:
                    label:     Priority
                    type:      choice
                    data_name: issuePriority.name
                    options:
                        field_options:
                            choices: @oro_issue.grid_helper->getPriorityChoices()
                resolution:
                    label:     Resolution
                    type:      choice
                    data_name: issue.resolution
                    options:
                        field_options:
                            choices: @oro_issue.grid_helper->getResolutionChoices()
                reporter:
                    label:     Reporter
                    type:      string
                    data_name: issueReporterName
                assignee:
                    label:     Assignee
                    type:      string
                    data_name: issueAssigneeName
                createdAt:
                    type:      datetime
                    data_name: issue.createdAt
                updatedAt:
                    type:      datetime
                    data_name: issue.updatedAt
        properties:
            id: ~
            view_link:
                type:       url
                route:      oro_issue_view
                params:     [ id ]
            update_link:
                type:       url
                route:      oro_issue_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      oro_api_delete_issue
                params:     [ id ]
        actions:
            view:
                type:          navigate
                acl_resource:  oro_issue_view
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  oro_issue_update
                label:         oro.grid.action.update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  oro_issue_delete
                label:         oro.grid.action.delete
                icon:          trash
                link:          delete_link
        options:
            entity_pagination: true

    parents-issue-grid:
        extends: issue-grid
        source:
            query:
                where:
                    and:
                        - issue.parent IS NULL
        filters: ~

    sub-issue-grid:
        extends: issue-grid
        source:
            query:
                where:
                    and:
                        - issue.parent = :parent_id
            bind_parameters:
                - parent_id
        filters: ~
        options:
            toolbarOptions:
                hide: true

    assignee-issue-grid:
        extends: issue-grid
        source:
            query:
                where:
                    and:
                        - issue.assignee = :assignee_id
            bind_parameters:
                - assignee_id
        filters: ~
        options:
            toolbarOptions:
                hide: true

    collaborators-grid:
        source:
            type: orm
            acl_resource: oro_issue_view
            query:
                select:
                    - collaborators.id
                    - CONCAT(collaborators.firstName, CONCAT(' ', collaborators.lastName)) as name
                from:
                    - { table: %oro_issue.entity.class%, alias: issue }
                join:
                    left:
                         - { join: issue.collaborators, alias: collaborators }
                where:
                    and:
                        - issue.id = :issue_id
            bind_parameters:
                - issue_id
        columns:
            name:
                label:         oro.issue.collaborator_name_label
            step:
                renderable: false

    widget-short-issue-grid:
        source:
            type: orm
            acl_resource: oro_issue_view
            query:
                select:
                    - issue.id
                    - issue.code
                    - issue.summary
                from:
                    - { table: %oro_issue.entity.class%, alias: issue }
                join:
                    inner:
                         - { join: issue.collaborators, alias: collaborators }
                         - { join: issue.workflowStep, alias: workflowStep }
                where:
                    and:
                        - collaborators.id = :user_id
                        - workflowStep.name NOT IN ('resolved', 'closed')
            bind_parameters:
                - user_id
        columns:
            code:
                label:         oro.issue.code_label
            summary:
                label:         oro.issue.summary_label
        options:
            entity_pagination: true
            toolbarOptions:
                hide: true
                pageSize:
                    items: [10]
                    default_per_page: 10