parameters:
    oro_issue.importexport.template_fixture.issue.class: Oro\Bundle\IssueBundle\ImportExport\TemplateFixture\IssueFixture

services:
    # Converter
    oro_issue.importexport.data_converter.issue:
        parent: oro_importexport.data_converter.configurable

    oro_issue.importexport.template_fixture.data_converter.issue:
        parent: oro_importexport.data_converter.template_fixture.configurable

    # Strategy
    oro_issue.importexport.strategy.issue.add_or_replace:
        parent: oro_importexport.strategy.configurable_add_or_replace
        
    # Import processor
    oro_issue.importexport.processor.import.issue:
        parent: oro_importexport.processor.import_abstract
        calls:
          - [setDataConverter, [@oro_issue.importexport.data_converter.issue]]
          - [setStrategy, [@oro_issue.importexport.strategy.issue.add_or_replace]]
        tags:
          - { name: oro_importexport.processor, type: import, entity: %oro_issue.entity.class%, alias: oro_issue }
          - { name: oro_importexport.processor, type: import_validation, entity: %oro_issue.entity.class%, alias: oro_issue }

    # Export processor
    oro_issue.importexport.processor.export.issue:
        parent: oro_importexport.processor.export_abstract
        calls:
          - [ setDataConverter, [@oro_issue.importexport.data_converter.issue]]
        tags:
          - { name: oro_importexport.processor, type: export, entity: %oro_issue.entity.class%, alias: oro_issue }

    oro_issue.importexport.processor.export_template.issue:
        parent: oro_importexport.processor.export_abstract
        calls:
          - [setDataConverter, [@oro_issue.importexport.template_fixture.data_converter.issue]]
        tags:
          - { name: oro_importexport.processor, type: export_template, entity: %oro_issue.entity.class%, alias: oro_issue }

    # Export template
    oro_issue.importexport.template_fixture.issue:
        class: %oro_issue.importexport.template_fixture.issue.class%
        tags:
          - { name: oro_importexport.template_fixture }