oro_menu_config:
    items:
        issue_list:
            label: 'oro.issue.entity_plural.label'
            route: 'oro_issue_index'
            extras:
                position: 1
    tree:
        application_menu:
            children:
                activities_tab:
                    children:
                        issue_list: ~