oro_menu_config:
    items:
        issue_list:
            label: 'oro.issue.entity_plural.label'
            route: 'oro_issue_index'
            extras:
                position: 1
        shortcut_new_issue:
            label: 'oro.menu.shortcut_new_issue.label'
            route: 'oro_issue_create'
            extras:
                isCustomAction: true
    tree:
        application_menu:
            children:
                activities_tab:
                    children:
                        issue_list: ~
        shortcuts:
            children:
                shortcut_new_issue: ~
