placeholders:
    view_content_data_additional_information:
        items:
            oro_issue_list: ~

items:
    oro_issue_list:
        template: OroIssueBundle:User:assignee_issues_list.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)