oro_issue_bundle:
    resource:     "@IssueBundle/Controller"
    type:         annotation
    prefix:       /issue

oro_issue_bundle_api:
    resource:     "@IssueBundle/Controller/Api/Rest/IssueController.php"
    type:         rest
    prefix:       /issue/api/rest/{version}
    requirements:
        version:  latest|v1
    defaults:
        version:  latest